// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyW2ZEH6DtwtF62tNCgdPgBcXIXoSJFpU',
    appId: '1:1044341798763:web:f5199d37200f2ba088fe2e',
    messagingSenderId: '1044341798763',
    projectId: 'jasper-health-weight-tracker',
    authDomain: 'jasper-health-weight-tracker.firebaseapp.com',
    storageBucket: 'jasper-health-weight-tracker.appspot.com',
    measurementId: 'G-DNFWRHWYHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvfQ1CzUOZX08jJml55XjAh2UneUQpSmo',
    appId: '1:1044341798763:android:87f75f514f5a96f688fe2e',
    messagingSenderId: '1044341798763',
    projectId: 'jasper-health-weight-tracker',
    storageBucket: 'jasper-health-weight-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBog3_D9QmdwlviAS9AL1Gl-epqfEVyCes',
    appId: '1:1044341798763:ios:dce3874c39d715c188fe2e',
    messagingSenderId: '1044341798763',
    projectId: 'jasper-health-weight-tracker',
    storageBucket: 'jasper-health-weight-tracker.appspot.com',
    iosBundleId: 'com.gthompson333.weight-tracker',
  );
}
